version: '3'
services:
  react:
    build: ./react
    links:
      - mysql
    ports:
      - "8080:3000"
    volumes:
      - ./react/data:/var/www/html
    depends_on:
      - mysql
    tty: true
    privileged: true

  mysql:
    build: ./mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 8081:80
    depends_on:
      - mysql